### PR TITLE
AUI-VIDEO Responsive aspect added to video

### PR DESCRIPTION
**Pull request by tylerwonglr**
Hey Jon!

Please check the PR!  Added the responsive aspect to the aui-video module.

Thanks,
Tyler

### CODE REVIEW

**Comment by juangon** [comment]
Hi @tylerwonglr . Seems this only would resize if Window is decreased, but not increased, right? Wouldn't be better to configure some flag to resize to whatever window size is?

Thanks for your pull!

**Comment by juangon** [comment]
Hi @jonmak08. Any chance to review this pull? After this fix Antonio could continue the fix for CKEditor. Would be great to have this on GA2 (so should be committed in 2 weeks approx.)

Thanks Jon!

**Comment by jonmak08** [comment]
Hey @juangon,

Sure thing.  I will get this in to GA2.  Thanks!

**Comment by juangon** [comment]
Hi @jonmak08 I think we are very tight for GA2 now. Any chance to review this? Thanks.

**Comment by juangon** [comment]
Hi @jonmak08. Don't hurry, seems GA2 is freezed now.

**Comment by jonmak08** [comment]
Hey @juangon,

They are going to release another beta this week for GA2.  It looks like it is not frozen.  I am actually reviewing this right now, but had to refactor some of it, which is why it is taking longer than originally anticipated.

I should have this done by end of the day or tomorrow.

Please let me know if you have any questions. Thanks!

**Comment by juangon** [comment]
Thanks for the effort Jon. Much appreciated as always...

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/thiago-rocha/alloy-ui/pull/86

View just my changes: https://github.com/jonmak08/alloy-ui/compare/tylerwonglr:ed9bf8cfde...3d108151ce
View total diff: https://github.com/jonmak08/alloy-ui/compare/9ff0c8728a...3d108151ce

**Pull request closed without merging**
