### PR TITLE
AUI-3099 Using 'makeImageVisible' behavior to update scroll position …

### PR DESCRIPTION
**Pull request by gregory-bretall**
…of thumbnail list

Resent from https://github.com/dustinryerson/alloy-ui/pull/4#issue-212375643

/cc @zsagia

### CODE REVIEW

**Comment by jonmak08** [comment]
This does not actually solve the issue since on a smaller screen, the image gallery is still blocked by the list of images.  See the screenshot below:

image

**Comment by gregory-bretall** [comment]
Thanks for letting me know, I'm closing this and resending it back to @zsagia to fix the issue.

**Comment by jonmak08** [comment]
I think you can take a shot at fixing this issue by doing the following:

In ```aui-image-viewer-base.js```, we have a method ```_displayLoadedImage``` which has a call to ```instance._setAlignCenter(true);``` (https://github.com/liferay/alloy-ui/blob/2.0.x/src/aui-image-viewer/js/aui-image-viewer-base.js#L753).  I think if you override the ```_displayLoadedImage``` method in ```aui-image-viewer-gallery.js``` since it extends ```A.ImageViewer```.

Then in your overriden method inside of ```aui-image-viewer-gallery.js``` you can call something like 
```
instance._uiSetAlign(
    instance.get(PAGINATION_EL),
    [
        'tc', 'bc'
    ]
);
```

The points that you want to be aligned against will need some tweaking, but try that and see if it works.

Your overridden method might look something like:

```
_displayLoadedImage: function(image) {
    var instance = this;

    ImageGallery.superclass._displayLoadedImage.apply(this, arguments);

    var paginationEl = instance.get(PAGINATION_EL);

    instance._uiSetAlign(
        paginationEl,
        [
            'bc', 'bl'
        ]
    );
},
```

**Comment by jonmak08** [comment]
Hey @gregory-bretall,

@zsagia has actually left Liferay so if you want to take a crack at fixing this and sending me an updated pull that would be good.

Please let me know if you have any questions. Thanks!

**Comment by gregory-bretall** [comment]
Hi @jonmak08 thanks for letting me know, I'll try and work on implementing the fix you suggested next week and I'll send you a PR when it's done.

**Pull request closed without merging**
