### PR TITLE
AUI-1353 Datepicker

### PR DESCRIPTION
**Pull request by protoEvangelion**
Need to write tests and add additional keyboard functionality to double pane calendar for multiple date selection.

### CODE REVIEW

**Comment by jonmak08** [comment]
Reviewed and Merged.  Thanks!

Please see my changes at https://github.com/liferay/alloy-ui/compare/dcb2d554ad53b705c1a9452e6077c24ae541f0ad...f2e174f9156efa4bc988677cf227075b7d9756d5.

**Comment by jonmak08** [comment]
Keeping open for now since I still have to review the unit test.

**Comment by protoEvangelion** [comment]
Looks great!

**Comment by jonmak08** [comment]
Closing pull request.

**Pull request closed without merging**
