### PR TITLE
AUI-1958

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
@sergiogonzalez when you get back, can you take a look at this? I've sent you an email asking about AUI-533 and this ticket undoing that.

/cc @natecavanaugh

**Comment by blzaugg** [comment]
Jon, I expect LPS-58084 & LPS-58127 to go into Portal with AUI-1958

**Comment by jonmak08** [comment]
Waiting on the pull for LPS-58127.  When reviewing LPS-58127, add the new AUI zip which includes AUI-1958 as a another commit.

**Comment by blzaugg** [comment]
Portal: https://github.com/jonmak08/liferay-portal/pull/1332

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/thiago-rocha/alloy-ui/pull/22
View total diff: https://github.com/jonmak08/alloy-ui/compare/9b718e8b4c...3315c7aa85

**Pull request closed without merging**
