### PR TITLE
[TECHNICAL REQUEST] backport 2.0.x AUI-2037 AUI-2038

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Jon,

It is Byran's pull request. Could you review it?

I tested and it worked however I found some css issues but those were probably because of there are some mess in my PC.

You have tested this when you helped us to check the pull at here:
https://github.com/peterborkuti/alloy-ui/pull/4

Thank you in advance
Péter

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey guys,

I will review this tomorrow and keep you updated.

Please let me know if you have any questions. Thanks!

**Comment by marcellustavares** [comment]
hey @jonmak08 @peterborkuti, any updates regarding this pull?

Thanks

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/mairatma/alloy-ui/pull/299

View just my changes: https://github.com/jonmak08/alloy-ui/compare/peterborkuti:b8157afe56...bbc4ea9cf7
View total diff: https://github.com/jonmak08/alloy-ui/compare/5689f765b5...bbc4ea9cf7

**Comment by jonmak08** [comment]
Sent to @mairatma for review.

**Comment by jonmak08** [comment]
Pushing into 2.0.x since this is just a backport to 2.0.x with minor modifications.

**Pull request closed without merging**
